# -*- coding: utf-8 -*-
"""petrophysics02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwomZhSvjrx58CfBKWbifQKsxUD4iZYR

**Instruction.** Run the cells from the beginning.

**Your task**

```
# Import Lasio library
___

# Specify file path
filepath = ___

# Read with lasio
las = lasio.read(___)
```
"""

#@title Run this first { display-mode: "form" }
!pip -q install lasio
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Specify file path
filepath = 'https://raw.githubusercontent.com/yohanesnuwara/formation-evaluation/main/data/volve/15_9-F-11A.LAS'

# Read with lasio
las = lasio.read(filepath)